### ISSUE TITLE
AST documentation

### ISSUE THREAD

**Issue by parro-it** [vorpaljs/bash-parser#25]
After various refactoring of the AST structure I did in the last days, I think it should be pretty stable now.
I wrote some documentation of format [here](https://github.com/vorpaljs/bash-parser/blob/master/docs/ast.md). 

Please help me checking my english :smiley_cat: 

Any improve needed?

**Comment by wooorm** [comment]
Looks good! I checked pretty quickly, but here are some things I found:

* [subshell](https://github.com/vorpaljs/bash-parser/blob/master/docs/ast.md#subshell) section has malformed markdown code blocks;
* Maybe rename `and_or` to “logical operator” or something?
* “simple command” > “builtIn”?
* “io_redirect” > “redirect”?
* “complete_command” > “root”?

And regarding the AST: I’d go with camelCased instead of snake_cased. Practical use case: so you can later have functions that generate nodes, like so: `b.caseItem(pattern, body)`, and don’t need to have a mental maping of these things.
I’d also suggest against using restricted keywords like [`if`](https://github.com/vorpaljs/bash-parser/blob/master/docs/ast.md#if) and [`do`](https://github.com/vorpaljs/bash-parser/blob/master/docs/ast.md#subshell)

Anyway, I don’t no much about ASTs for programming language, I’m mostly working on markup ASTs. But maybe check out [SpiderMonkey AST](https://developer.mozilla.org/en-US/docs/Mozilla/Projects/SpiderMonkey/Parser_API) / [Babel AST](https://github.com/babel/babylon/blob/master/ast/spec.md) and get as close as possible to that?

P.S. I’ll do English another time :)

**Comment by parro-it** [comment]
> Looks good! I checked pretty quickly, but here are some things I found:

Thank you for the check @wooorm !

> subshell section has malformed markdown code blocks;

Already noted, fixed...

> P.S. I’ll do English another time :)

Thank you again

Regarding all other issues regarding node type names, I agree with you. I keep same names as they appear on [POSIX standard grammar](http://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html) rules. 

This help me a lot during developing, but I admit they are weird and complicate the use cases you specified, so I probably refactor them as you suggested...
