### ISSUE TITLE
Unable to use keywords as arguments

### ISSUE THREAD

**Issue by nfischer** [vorpaljs/bash-parser#31]
I've noticed that I'm unable to parse the following commands:

```bash
sh $ echo if this then that # should print "if this then that"
```

Or the zsh-only code:

```bash
zsh $ alias if=echo
zsh $ if this then that # prints "this then that", same as `echo this then that` would
```

The zsh-only code may be hard to support, but the first one should definitely be supported.

**Comment by piranna** [comment]
Second one is just a matter of adding alias expansión, probably with a
callback.

El 11/9/2016 4:16 AM, "Nate Fischer" <notifications@github.com> escribió:

I've noticed that I'm unable to parse the following commands:

sh $ echo if this then that # should print "if this then that"

Or the zsh-only code:

zsh $ alias if=echo
zsh $ if this then that # prints "this then that", same as `echo this
then that` would

The zsh-only code may be hard to support, but the first one should
definitely be supported.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/vorpaljs/bash-parser/issues/31>, or mute the thread

**Comment by parro-it** [comment]
The first command should be correctly parsed accordingly to POSIX, so it's a bug.

The standard related  part is here: http://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_04

We have to identify a TOKEN as a reserved word only in these situation:

* The first word of a command

* The first word following one of the reserved words other than case, for, or in

* The third word in a case command (only in is valid in this case)

* The third word in a for command (only in and do are valid in this case)

Instead, I'm actually transforming every word that match a reserved word. Relevant code is [here](https://github.com/vorpaljs/bash-parser/blob/master/src/tokenization-rules.js#L53)

**Comment by parro-it** [comment]
The second command should work when we solve the problem above, since the `if` would be identify as a WORD and alias expansion should work consequently.

@piranna : alias expansion is already implemented: here are [the source code](https://github.com/vorpaljs/bash-parser/blob/master/src/alias-substitution.js), [tests](https://github.com/vorpaljs/bash-parser/blob/master/test/test-alias-substitution.js) and [API docs](https://github.com/vorpaljs/bash-parser/blob/master/documents/api.md)

**Comment by piranna** [comment]
> @piranna : alias expansion is already implemented: here are the source code, tests and API docs

So there you are :-)

**Comment by parro-it** [comment]
Solved this as specified above, regarding second @nfischer example: 

```bash
zsh $ alias if=echo
zsh $ if this then that # prints "this then that", same as `echo this then that` would
```

You are now be able to parse the first command `alias if=echo`, but not the second, because POSIX standard says that alias shall not be expanded on reserved words, so `if this then that` is not interpreted as a call to `if` alias.

This is also a bash extension (see #35), so I prefer to add it on a second phase of the project, when the POSIX core is more robust.

**Comment by nfischer** [comment]
:+1: Sounds like a good move
